.TH "headers Directory Reference" 3 "Mon Apr 22 2019" "Version 1.1" "Timberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBassets\&.h\fP"
.br
.ti -1c
.RI "file \fBgame\&.h\fP"
.br
.ti -1c
.RI "file \fBplayer\&.h\fP"
.br
.ti -1c
.RI "file \fBtext\&.h\fP"
.br
.ti -1c
.RI "file \fBwindow\&.h\fP"
.br
.in -1c
