.TH "headers/game.h" 3 "Mon Apr 22 2019" "Version 1.1" "Timberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/game.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include 'window\&.h'\fP
.br
\fC#include 'assets\&.h'\fP
.br
\fC#include 'player\&.h'\fP
.br
\fC#include 'text\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGame\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFRAMES_PER_SECOND\fP   60\&.0"
.br
.ti -1c
.RI "#define \fBWINDOW_WIDTH\fP   900"
.br
.ti -1c
.RI "#define \fBWINDOW_HEIGHT\fP   1024"
.br
.ti -1c
.RI "#define \fBDEFAULT_GAME_TIME\fP   8\&.0"
.br
.ti -1c
.RI "#define \fBTIME_INCREMENT\fP   0\&.15"
.br
.ti -1c
.RI "#define \fBTEXT_SIZE\fP   23"
.br
.ti -1c
.RI "#define \fBTEXT_POS_X\fP   100"
.br
.ti -1c
.RI "#define \fBTEXT_POS_Y\fP   24"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_GAME_TIME   8\&.0"

.PP
Definition at line 64 of file game\&.h\&.
.PP
Referenced by Game::Game()\&.
.SS "#define FRAMES_PER_SECOND   60\&.0"

.PP
Definition at line 59 of file game\&.h\&.
.PP
Referenced by Game::update()\&.
.SS "#define TEXT_POS_X   100"

.PP
Definition at line 69 of file game\&.h\&.
.PP
Referenced by Game::Game()\&.
.SS "#define TEXT_POS_Y   24"

.PP
Definition at line 70 of file game\&.h\&.
.PP
Referenced by Game::Game()\&.
.SS "#define TEXT_SIZE   23"

.PP
Definition at line 68 of file game\&.h\&.
.PP
Referenced by Game::Game()\&.
.SS "#define TIME_INCREMENT   0\&.15"

.PP
Definition at line 65 of file game\&.h\&.
.PP
Referenced by Game::handle_input()\&.
.SS "#define WINDOW_HEIGHT   1024"

.PP
Definition at line 61 of file game\&.h\&.
.SS "#define WINDOW_WIDTH   900"

.PP
Definition at line 60 of file game\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Timberman from the source code\&.
