.TH "md__r_e_a_d_m_e" 3 "Mon Apr 22 2019" "Version 1.1" "Timberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_eTimberman 
 \- 
.SS "About"
.PP
Simple 2D arcade style casual game\&. Chop wood, avoid branches, git gud\&. Written in C++/SFML\&.
.PP
.SS "Dependencies"
.PP
.IP "\(bu" 2
g++ or any other compiler with C++14 support
.IP "\(bu" 2
make
.IP "\(bu" 2
SFML >= 2\&.5
.PP
.PP
.SS "Compilation"
.PP
.SS "Linux"
.PP
.PP
.nf
git clone https://github\&.com/juhito/sfml-peli\&.git
cd sfml-peli
make
.fi
.PP
.PP
.SS "Windows"
.PP
I personally haven't tested this on windows, it should work but I don't guarantee anything\&. 
