.TH "headers/player.h" 3 "Mon Apr 22 2019" "Version 1.1" "Timberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/player.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include 'assets\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPlayer\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPLAYER_POS_LX\fP   100"
.br
.ti -1c
.RI "#define \fBPLAYER_POS_RX\fP   500"
.br
.ti -1c
.RI "#define \fBPLAYER_POS_Y\fP   1050"
.br
.ti -1c
.RI "#define \fBPLAYER_ORIGIN_RX\fP   300"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PLAYER_ORIGIN_RX   300"

.PP
Definition at line 58 of file player\&.h\&.
.PP
Referenced by Player::handle_input()\&.
.SS "#define PLAYER_POS_LX   100"

.PP
Definition at line 55 of file player\&.h\&.
.PP
Referenced by Player::handle_input(), and Player::init()\&.
.SS "#define PLAYER_POS_RX   500"

.PP
Definition at line 56 of file player\&.h\&.
.PP
Referenced by Player::handle_input()\&.
.SS "#define PLAYER_POS_Y   1050"

.PP
Definition at line 57 of file player\&.h\&.
.PP
Referenced by Player::handle_input(), and Player::init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Timberman from the source code\&.
