.TH "headers/window.h" 3 "Mon Apr 22 2019" "Version 1.1" "Timberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/window.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBM_VIEW_X\fP   900\&.0"
.br
.ti -1c
.RI "#define \fBM_VIEW_Y\fP   1600\&.0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define M_VIEW_X   900\&.0"

.PP
Definition at line 52 of file window\&.h\&.
.PP
Referenced by Window::handle_events()\&.
.SS "#define M_VIEW_Y   1600\&.0"

.PP
Definition at line 53 of file window\&.h\&.
.PP
Referenced by Window::handle_events()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Timberman from the source code\&.
