Window Class Reference
#include <window.h>
Public Member Functions
Window ()
Default constructor for window.
Window (const std::string &title, const sf::Vector2u &size)
Constructor with parameters for calling the setup method.
~Window ()
void begin_draw ()
Function to start drawing (clears the screen)
void end_draw ()
Function to end drawing (displays everything that's been drawed)
void handle_events (sf::Event &event)
Function to poll events and handle them.
bool is_done ()
Function to check if we should close the window.
sf::Event & get_event ()
Function to get the event member variable.
sf::RenderWindow * get_render_window ()
Function to get the current window.
sf::Vector2u get_window_size ()
Function to get the window size.
void draw (sf::Drawable &asset)
Function to draw everything to the screen.
Detailed Description
Definition at line 55 of file window.h.
Constructor & Destructor Documentation
Window() [1/2]
Window::Window ()
Default constructor for window.
Definition at line 3 of file window.cc.
               {
    this->setup("Window", {640, 480});
}
Window() [2/2]
Window::Window (const std::string & title, const sf::Vector2u & size)
Constructor with parameters for calling the setup method.
Parameters
title Window title
size Window size
Definition at line 7 of file window.cc.
                                                             {
    this->setup(title, size);
}
 Window()
Window::~Window ()
Definition at line 11 of file window.cc.
                {
    this->destroy();
}
Member Function Documentation
begin_draw()
void Window::begin_draw ()
Function to start drawing (clears the screen)
Returns
void
Definition at line 49 of file window.cc.
Referenced by Game::render().
                        {
    m_window.clear(sf::Color::Black);
}
draw()
void Window::draw (sf::Drawable & asset)
Function to draw everything to the screen.
Parameters
asset Any asset that is child of Drawable
Returns
void
Definition at line 65 of file window.cc.
                                   {
    m_window.draw(asset);
}
end_draw()
void Window::end_draw ()
Function to end drawing (displays everything that's been drawed)
Returns
void
Definition at line 53 of file window.cc.
Referenced by Game::render().
                      {
    m_window.display();
}
get_event()
sf::Event Window::get_event ()
Function to get the event member variable.
Returns
Reference to the event member variable
Definition at line 73 of file window.cc.
Referenced by Game::handle_events().
                           {
    return(m_event);
}
get_render_window()
sf::RenderWindow * Window::get_render_window ()
Function to get the current window.
Returns
Pointer to the window
Definition at line 69 of file window.cc.
Referenced by Game::handle_events(), and Game::render().
                                          {
    return(&m_window);
}
get_window_size()
sf::Vector2u Window::get_window_size ()
Function to get the window size.
Returns
Returns the dimensions of the window as Vector2u
Definition at line 61 of file window.cc.
Referenced by Game::update().
                                   {
    return(m_wsize);
}
handle_events()
void Window::handle_events (sf::Event & event)
Function to poll events and handle them.
Parameters
event Current event to handle
Returns
void
Definition at line 22 of file window.cc.
References M_VIEW_X, and M_VIEW_Y.
Referenced by Game::handle_events().
                                         {
    switch(event.type) {
        case sf::Event::Closed:
            m_done = true;
            break;
        case sf::Event::KeyPressed:
            if(event.key.code == sf::Keyboard::Escape)
                m_done = true;
            break;
    }
}
is_done()
bool Window::is_done ()
Function to check if we should close the window.
Returns
true if we should close, false otherwise
Definition at line 57 of file window.cc.
Referenced by main().
                     {
    return(m_done);
}
The documentation for this class was generated from the following files:
headers/window.h
window.cc