Player Class Reference
#include <player.h>
Public Member Functions
Player ()
~Player ()
void init ()
Function to init textures and positions for this class.
int get_score ()
Function to get player's score.
side get_side ()
Function to get player's side.
void increment_score ()
Function to increment player's score.
void lose ()
Function to make player lose.
bool has_lost ()
Function to check if you've lost.
void draw (sf::RenderWindow &window)
Function to draw everything to screen.
void update (Assets &asset, sf::Time &dt)
Function to animate player and check if you've lost.
void handle_input (sf::Event &event)
Function to handle player input.
Detailed Description
Definition at line 63 of file player.h.
Constructor & Destructor Documentation
Player()
Player::Player ()
Definition at line 3 of file player.cc.
{}
 Player()
Player::~Player ()
Definition at line 5 of file player.cc.
{}
Member Function Documentation
draw()
void Player::draw (sf::RenderWindow & window)
Function to draw everything to screen.
Parameters
window Drawable window
Returns
void
Definition at line 89 of file player.cc.
Referenced by Game::render().
                                        {
    window.draw(m_sprite);
}
get_score()
int Player::get_score ()
Function to get player's score.
Returns
current score
Definition at line 21 of file player.cc.
Referenced by Assets::handle_input(), and Game::update().
                      {
    return(m_score);
}
get_side()
side Player::get_side ()
Function to get player's side.
Returns
player's side which is an enum
Definition at line 25 of file player.cc.
                      {
    return(m_side);
}
handle_input()
void Player::handle_input (sf::Event & event)
Function to handle player input.
Parameters
event Event class by reference for getting the current event
Returns
void
Definition at line 41 of file player.cc.
References increment_score(), LEFT, PLAYER_ORIGIN_RX, PLAYER_POS_LX, PLAYER_POS_RX, PLAYER_POS_Y, and RIGHT.
Referenced by Game::handle_events().
                                        {
    if(event.type == sf::Event::KeyPressed) {
        if(event.key.code == sf::Keyboard::Left && m_input) {
            m_side = side::LEFT;
            this->increment_score();
            if(m_side == side::LEFT) {
                m_sprite.setTexture(m_anim);
                m_sprite.setScale(1.f, 1.f); // change orientation to normal
                m_sprite.setOrigin(0, 0);
                m_sprite.setPosition(PLAYER_POS_LX, PLAYER_POS_Y);
            }
        }
        else if(event.key.code == sf::Keyboard::Right && m_input) {
            m_side = side::RIGHT;
            this->increment_score();
            if(m_side == side::RIGHT) {
                m_sprite.setTexture(m_anim);
                m_sprite.setScale(-1.f, 1.f); // change orientation
                m_sprite.setOrigin(PLAYER_ORIGIN_RX, 0);
                m_sprite.setPosition(PLAYER_POS_RX, PLAYER_POS_Y);
            }
        }
        m_input = false;
    }
    if(event.type == sf::Event::KeyReleased)
        m_input = true;
}
has_lost()
bool Player::has_lost ()
Function to check if you've lost.
Returns
true if lost, false otherwise
Definition at line 37 of file player.cc.
Referenced by Game::handle_events(), Game::handle_input(), and Game::update().
                      {
    return(m_lost);
}
increment_score()
void Player::increment_score ()
Function to increment player's score.
Returns
void
Definition at line 29 of file player.cc.
Referenced by handle_input().
                             {
    m_score++;
}
init()
void Player::init ()
Function to init textures and positions for this class.
Returns
void
Definition at line 7 of file player.cc.
References LEFT, PLAYER_POS_LX, and PLAYER_POS_Y.
Referenced by Game::Game().
                  {
    m_texture.loadFromFile("assets/tm.png");
    m_texture.setSmooth(true);
    m_anim.loadFromFile("assets/tm2.png");
    m_anim.setSmooth(true);
    m_sprite.setTexture(m_texture);
    m_sprite.setPosition(PLAYER_POS_LX, PLAYER_POS_Y);
    m_side = side::LEFT;
    m_score = 0;
    m_lost = false;
    m_duration = 0;
    m_input = true;
}
lose()
void Player::lose ()
Function to make player lose.
Returns
void
Definition at line 33 of file player.cc.
Referenced by Game::update(), and update().
                  {
    m_lost = true;
}
update()
void Player::update (Assets & asset, sf::Time & dt)
Function to animate player and check if you've lost.
Parameters
asset For getting bounds of the last branch
dt Calculated delta time
Returns
void
Definition at line 70 of file player.cc.
References Assets::get_branch_bounds(), lose(), and NONE.
Referenced by Game::update().
                                             {
    /*
     * NOTE:
     * The implementation of animating is awful but it was probably /
     * the only way of doing this without creating a whole animation manager system.
     */
    if(m_side != side::NONE) {
        m_duration += dt.asSeconds();
        if(m_duration > 0.2f) {
            m_duration = 0;
            m_sprite.setTexture(m_texture);
        }
    }
    
    if(m_sprite.getGlobalBounds().intersects(asset.get_branch_bounds())) {
        this->lose();
    }
}
The documentation for this class was generated from the following files:
headers/player.h
player.cc