Game Class Reference
#include <game.h>
Public Member Functions
Game ()
~Game ()
sf::Time get_elapsed ()
Function to get elapsed time.
void restart_clock ()
Function to restart the clock.
void update ()
Function to update game logic.
void handle_input (sf::Event event)
Function to handle input.
void handle_events ()
Function to poll events and handle them around.
void render ()
Function to draw everything to the screen.
Window * get_window ()
Function to get private member variable.
Detailed Description
Definition at line 72 of file game.h.
Constructor & Destructor Documentation
Game()
Game::Game ()
Definition at line 3 of file game.cc.
References Text::add(), DEFAULT_GAME_TIME, Player::init(), Assets::init(), Text::setup(), TEXT_POS_X, TEXT_POS_Y, and TEXT_SIZE.
           : m_window("Timber", sf::Vector2u(WINDOW_WIDTH,
      WINDOW_HEIGHT)) {
    m_asset.init();
    m_player.init();
    m_time.setup(TEXT_SIZE, sf::Vector2f(TEXT_POS_X, 0));
    m_score.setup(TEXT_SIZE, sf::Vector2f(TEXT_POS_X,
      TEXT_POS_Y));
    m_time.add("Time Left" + std::to_string(m_time_left));
    m_score.add("Score: 0");
    m_time_left = DEFAULT_GAME_TIME;
}
 Game()
Game::~Game ()
Definition at line 13 of file game.cc.
{}
Member Function Documentation
get_elapsed()
sf::Time Game::get_elapsed ()
Function to get elapsed time.
Returns
Elapsed time since clock restart
Definition at line 78 of file game.cc.
                         {
    return(m_elapsed);
}
get_window()
Window * Game::get_window ()
Function to get private member variable.
Returns
Pointer to the window class
Definition at line 74 of file game.cc.
Referenced by main().
                         {
    return(&m_window);
}
handle_events()
void Game::handle_events ()
Function to poll events and handle them around.
Returns
void
Definition at line 41 of file game.cc.
References Window::get_event(), Window::get_render_window(), Window::handle_events(), handle_input(), Player::handle_input(), Assets::handle_input(), and Player::has_lost().
Referenced by main().
                         {
    sf::Event event = m_window.get_event();
    while(m_window.get_render_window()->pollEvent(event)) {
        m_window.handle_events(event);
        if(!m_player.has_lost()) {
            m_player.handle_input(event);
            m_asset.handle_input(m_player, m_score, event);
        }
        
        this->handle_input(event);
    }
}
handle_input()
void Game::handle_input (sf::Event event)
Function to handle input.
Parameters
event Current event to handle
Returns
void
Definition at line 54 of file game.cc.
References Player::has_lost(), and TIME_INCREMENT.
Referenced by handle_events().
                                     {
    // input handling
    if(event.type == sf::Event::KeyPressed)
        if((event.key.code == sf::Keyboard::Left || event.key.code == sf::Keyboard::Right)
           && !m_player.has_lost())
            m_time_left += TIME_INCREMENT;
}
render()
void Game::render ()
Function to draw everything to the screen.
Returns
void
Definition at line 63 of file game.cc.
References Window::begin_draw(), Text::draw(), Player::draw(), Assets::draw(), Window::end_draw(), and Window::get_render_window().
Referenced by main().
                  {
    m_window.begin_draw();
    m_asset.draw(*m_window.get_render_window());
    m_player.draw(*m_window.get_render_window());
    m_time.draw(*m_window.get_render_window());
    m_score.draw(*m_window.get_render_window());
    m_window.end_draw();
}
restart_clock()
void Game::restart_clock ()
Function to restart the clock.
Returns
void
Definition at line 82 of file game.cc.
Referenced by main().
                         {
    m_elapsed += m_clock.restart();
}
update()
void Game::update ()
Function to update game logic.
Returns
void
Definition at line 15 of file game.cc.
References Text::add(), FRAMES_PER_SECOND, Player::get_score(), Window::get_window_size(), Player::has_lost(), Player::lose(), Assets::update(), and Player::update().
Referenced by main().
                  {
    sf::Vector2u wsize = m_window.get_window_size();
    float timestep = 1.0f / FRAMES_PER_SECOND;
    // 60 frames per second
    if(m_elapsed.asSeconds() >= timestep) {
        if(!m_player.has_lost()) {
            m_asset.update(m_elapsed);
            m_player.update(m_asset, m_elapsed);
            
            if(m_time_left < 0.01f)
                m_player.lose();
            else
                m_time_left -= m_elapsed.asSeconds();
            
            m_time.add("Time Left: " + std::to_string(m_time_left));
            m_elapsed -= sf::seconds(timestep);
        }
        else {
            m_time.add("YOU LOST!");
            m_score.add("Score: " + std::to_string(m_player.get_score()));
        }
    }
}
The documentation for this class was generated from the following files:
headers/game.h
game.cc