timber.cc File Reference
#include `headers/game.h`
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 14 of file timber.cc.
References Game::get_window(), Game::handle_events(), Window::is_done(), Game::render(), Game::restart_clock(), and Game::update().
               {
    Game game;
    while(!game.get_window()->is_done()) {
        game.handle_events();
        game.update();
        game.render();
        game.restart_clock();
    }
    return(0);
}